name: first workflow
 on:
    push:
     branches:
     _"main"
jobs:
     first-workflow-job:
      name:first job
      run-on: ubuntu-lastest
      steps:
       -name: before checkout action
         run: ls
         shell: bash

       -name: chechout steps 
          uses: actions/checkout@v3  

        -name: after checkout action
         run: ls
         shell: bash



   