name: first workflow
 on:
    push:
     branches:
     _"main"
jobs:
     first-workflow-job:
      name:first job
      run-on: ubuntu-lastest
      steps:
       -name: run bash command
         run: echo "first workflow"
         shell: bash




   